# .github/workflow/ci.yaml
# CI configuration file that tells GitHub what to do when a commit is pushed.

name: CI

# Run the job whenever a commit is pushed to any branch
on: [push, pull_request]

jobs:
  # This job checks if the project can compile succesfully
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Setup PNPM 6
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.31.0
      - name: Setup Node 16
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build the project
        run: pnpm compile
  # This job checks if there are any lint issues in the code
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Setup PNPM 6
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.31.0
      - name: Setup Node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Lint code
        run: pnpm lint
  # This job ensures that all the tests pass
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Setup PNPM 6
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.31.0
      - name: Setup Node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run tests
        run: pnpm run-s test:*
      - name: Upload test coverage and recordings
        uses: actions/upload-artifact@v2
        with:
          name: test-output
          path: |
            coverage/
            tests/assets/
